apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: photo-test
  name: photo-test
  selfLink: /api/v1/namespaces/default/services/photo-test
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: api
  - port: 5001
    protocol: TCP
    targetPort: 80
    name: ui
  selector:
    run: photo-test
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
